-- Suppression des anciennes tables Prisma
DROP TABLE IF EXISTS "_prisma_migrations" CASCADE;
DROP TABLE IF EXISTS "LineStop" CASCADE;
DROP TABLE IF EXISTS "Line" CASCADE;
DROP TABLE IF EXISTS "Stop" CASCADE;
DROP TABLE IF EXISTS "Category" CASCADE;
DROP TABLE IF EXISTS "User" CASCADE;
